// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250407121946_PreferencesFix")]
    partial class PreferencesFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.User.DisplayPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DisplayEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("DisplayFirstName")
                        .HasColumnType("bit");

                    b.Property<bool>("DisplayLastName")
                        .HasColumnType("bit");

                    b.Property<bool>("DisplayPhoneNumber")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DisplayPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
