  name: Build and deploy ASP.Net Core app to Azure Web App - PoZiomka
  on:
    push:
      branches:
        - main
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        
        - name: Set up .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.x'
        
        - name: Restore dependencies
          run: dotnet restore ./backend/backend.csproj
        
        - name: Build with dotnet
          run: dotnet build ./backend/backend.csproj --configuration Release --no-restore
        
        # - name: Run tests (if you have any)
        #   run: dotnet test --no-restore --verbosity normal
        #   continue-on-error: true
        
        - name: Clean publish directory before publish
          run: rm -rf ./publish/*

        - name: Publish
          run: dotnet publish ./backend/backend.csproj -c Release -o ./publish --no-restore --no-build
        
        - name: Show published files (debug)
          run: |
            echo "Published files:"
            ls -la ./publish/
            echo "Configuration files:"
            find ./publish -name "appsettings*.json" -ls
            echo "Main DLL:"
            find ./publish -name "backend.dll" -ls
        
        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v4
          with:
            name: .net-app
            path: ./publish

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      permissions:
        id-token: write
        contents: read
      
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: .net-app
        
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_476C6F11CE5B4E6A892DE5EBBD403235 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5B9A0D97E9EA4E53A40094EFFA6F1CD0 }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A83FF97406D7430AA8E8AC23398F2FD9 }}

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: 'PoZiomka'
            slot-name: 'Production'
            package: .
            